name: Push Branches
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
concurrency: ${{ github.workflow }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install pytest
      - run: pytest